### ISSUE TITLE
Fail convert https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types/axios/axios.d.ts

### ISSUE THREAD

**Issue by ScottHuangZL** [Kotlin/ts2kt#61]
**NullPointerException: null**
    at Object.throwNPE (C:\Users\scott_huang\AppData\Roaming\npm\node_modules\ts2kt\kotlin.js:3325:11)
    at TsClassToKt.visitClassDeclaration_4wvyue$ (C:\Users\scott_huang\AppData\Roaming\npm\node_modules\ts2kt\ts2kt.js:1956:114)
    at TypeScriptToKotlin.visitClassDeclaration_4wvyue$ (C:\Users\scott_huang\AppData\Roaming\npm\node_modules\ts2kt\ts2kt.js:2494:16)
    at visitNode (C:\Users\scott_huang\AppData\Roaming\npm\node_modules\ts2kt\ts2kt.js:1864:15)
    at C:\Users\scott_huang\AppData\Roaming\npm\node_modules\ts2kt\ts2kt.js:1840:7
    at visitEachNode (C:\Users\scott_huang\AppData\Roaming\npm\node_modules\ts2kt\node_modules\_typescript@2.0.10@typescript\lib\typescript.js:8343:30)
    at forEachChild (C:\Users\scott_huang\AppData\Roaming\npm\node_modules\ts2kt\node_modules\_typescript@2.0.10@typescript\lib\typescript.js:8503:24)
    at forEachChild_0 (C:\Users\scott_huang\AppData\Roaming\npm\node_modules\ts2kt\ts2kt.js:1844:5)
    at TypeScriptToKotlinBase.visitList_uvf806$ (C:\Users\scott_huang\AppData\Roaming\npm\node_modules\ts2kt\ts2kt.js:2846:5)
    at TypeScriptToKotlin.visitList_uvf806$ (C:\Users\scott_huang\AppData\Roaming\npm\node_modules\ts2kt\ts2kt.js:2720:56)

**Comment by bashor** [comment]
@ScottHuangZL what is the version of ts2kt do you use?

**Comment by ScottHuangZL** [comment]
0.0.14

**Comment by bashor** [comment]
Doesn't crash on macOS, will try on Windows

**Comment by bashor** [comment]
I can't reproduce it on windows too. Could you please attach the file that you try to convert and full log?

**Comment by ScottHuangZL** [comment]
Please get index.d.ts from below link
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/axios-mock-adapter

and run "ts2kt -d headers index.d.ts" to get the result

**Comment by bashor** [comment]
Works good to me for this declaration too

**Comment by ScottHuangZL** [comment]
I use node 9.2.0

Can you advise your steps for how to convert that index.d.ts? Thanks.

**Comment by bashor** [comment]
Nothing special:
install ts2kt@0.0.14
Download [axios-mock-adapter/index.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/axios-mock-adapter/index.d.ts) or [types/axios/axios.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types/axios/axios.d.ts)
mkdir "headers"
And run by `ts2kt -d headers index.d.ts`

**Comment by ScottHuangZL** [comment]
mh...
I will try to reinstall ts2kt again tonight and do last try.
It should be caused by node version... if still failed...

Btw, how about JB also maintain a kotlin headers for the top 50 popular/selected JS/Component header?

**Comment by bashor** [comment]
Yes, we are going to create a repository with declarations soon.
