### ISSUE TITLE
Cannot convert "material-ui" package

### ISSUE THREAD

**Issue by huston007** [Kotlin/ts2kt#67]
I'm trying to convert "material-ui" package which is located here: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/material-ui
I tried 0.18.5 version: `npm i @types/material-ui@0.18.5`

I use "ts2kt-automator" wrapper (but it just runs ts2kt by CLI command shown above)

But ts2kt fails with following output:
```
Running command:  /Users/***/Documents/github/create-react-kotlin-app/node_modules/ts2kt/ts2kt.js -d test/build/material-ui /Users/***/Documents/github/create-react-kotlin-app/packages/ts2kt-automator/node_modules/@types/material-ui/index.d.ts
ts2kt version: 0.0.16
Converting /Users/***/Documents/github/create-react-kotlin-app/packages/ts2kt-automator/node_modules/@types/material-ui/index.d.ts
Save declarations:
        test/build/material-ui/index.kt
        test/build/material-ui/index.__MaterialUI.kt
        test/build/material-ui/index.__MaterialUI.Styles.kt
        test/build/material-ui/index.__MaterialUI.propTypes.kt
        test/build/material-ui/index.__MaterialUI.BottomNavigation.kt
        test/build/material-ui/index.__MaterialUI.Card.kt
        test/build/material-ui/index.__MaterialUI.DatePicker.kt
        test/build/material-ui/index.__MaterialUI.GridList.kt
        test/build/material-ui/index.__MaterialUI.List.kt
        test/build/material-ui/index.__MaterialUI.Menus.kt
        test/build/material-ui/index.__MaterialUI.Popover.kt
        test/build/material-ui/index.__MaterialUI.Switches.kt
        test/build/material-ui/index.__MaterialUI.Stepper.kt
        test/build/material-ui/index.__MaterialUI.Table.kt
        test/build/material-ui/index.__MaterialUI.Tabs.kt
        test/build/material-ui/index.__MaterialUI.Toolbar.kt
        test/build/material-ui/index.__MaterialUI.Utils.kt
        test/build/material-ui/index.__MaterialUI.Utils.ColorManipulator.kt
        test/build/material-ui/index.material-ui/styles/colors.kt
ts2kt: exportedByAssignment should be empty, but it contains: [Dom, Tab, AvSubtitles, AvHd, Card, Chip, List, Menu, Tabs, ImageCameraRear, ImageCameraRoll, ContentCreate, TableBody, ActionNoteAdd, CommunicationChatBubble, ContentDrafts, CardText, ActionViewArray, AvMic, AvWeb, AvPlaylistAdd, Badge, MapsTraffic, ActionViewQuilt, AvPlayCircleOutline, Paper, Table, MapsAddLocation, EditorMonetizationOn, ActionQueryBuilder, HardwareCastConnected, ImageTimerOff, SocialLocationCity, ImageCameraFront, ImageLooksOne, ImageLooksTwo, SocialCake, SocialMood, SocialPoll, MapsLocalDining, ActionFavorite, MapsLocalLaundryService, ActionImportantDevices, ActionSettingsInputAntenna, HardwarePhoneIphone, NotificationDoNotDisturbAlt, NotificationDoNotDisturbOff, NotificationPhoneInTalk, AvSurroundSound, ActionGroupWork, NotificationSyncDisabled, ActionTheaters, DeviceBluetoothSearching, ImageSwitchVideo, ActionQuestionAnswer, PlacesKitchen, AvSlowMotionVideo, ImageExposure, NotificationPhoneLocked, PopoverAnimationDefault, ActionPermContactCalendar, MapsTram, EditorTextFields, NotificationPhoneMissed, ActionMotorcycle, ActionSettingsInputHdmi, ImageLeakRemove, ActionExitToApp, ActionViewList, ActionViewWeek, NotificationVoiceChat, AvEqualizer, NavigationArrowDropDownCircle, ActionSubject, NavigationExpandLess, NavigationExpandMore, CommunicationImportContacts, MapsDirections, Snackbar, NotificationPhonePaused, NotificationAirlineSeatIndividualSuite, MapsLocalGasStation, ActionSwapHoriz, FileCreateNewFolder, GridList, GridTile, ImageColorLens, ActionVisibilityOff, MapsLocalMovies, AvArtTrack, ActionTrendingUp, HardwarePhonelink, ImageBlurLinear, EditorShortText, FontIcon, ContentRemove, ContentReport, AvHearing, CommunicationCallMissedOutgoing, ActionRoundedCorner, ImageFilterNone, EditorSpaceBar, CommunicationInvertColorsOff, EditorAttachMoney, ActionSupervisorAccount, PlacesFitnessCenter, EditorInsertEmoticon, EditorModeComment, ActionCompareArrows, ActionSettings, SocialMoodBad, TableHeaderColumn, EditorBorderBottom, ImageBrush, Toolbar, EditorShowChart, ImageFlare, NotificationEnhancedEncryption, ImageGrain, ImageHdrOn, ImageImage, ImageLooks, ImageLoupe, ImagePhoto, ActionSettingsBluetooth, ActionPictureInPictureAlt, ImageStyle, ImageTimer, CommunicationPhonelinkErase, CommunicationPhonelinkSetup, ActionCardTravel, MapsPinDrop, CommunicationSwapCalls, MapsDirectionsTransit, ContentWeekend, ActionAlarmAdd, ActionAlarmOff, ToolbarGroup, ActionDashboard, EditorBorderLeft, FlatButton, ToolbarTitle, AvFiberDvr, AvFiberNew, AvFiberPin, ActionCardMembership, EditorWrapText, DeviceSignalCellularConnectedNoInternet0Bar, DeviceSignalCellularConnectedNoInternet1Bar, DeviceSignalCellularConnectedNoInternet2Bar, DeviceSignalCellularConnectedNoInternet3Bar, DeviceSignalCellularConnectedNoInternet4Bar, FileCloud, EditorTitle, NotificationBluetoothAudio, NotificationEventAvailable, AvMicNone, ActionFavoriteBorder, ActionBookmarkBorder, BottomNavigation, ActionSwapVerticalCircle, AvReplay5, NotificationAirlineSeatLegroomExtra, ImageCenterFocusStrong, PlacesSmokeFree, CommunicationStopScreenShare, ImageBlurOff, ActionHelpOutline, AvBrandingWatermark, ImageMovieFilter, NotificationMore, NotificationSync, NotificationWifi, RadioButton, NavigationArrowDownward, AvVideoCall, PlacesChildFriendly, HardwareLaptopMac, CommunicationCallMerge, ContentAddCircle, ImageLeakAdd, CommunicationCallSplit, AvPauseCircleOutline, ActionFlipToBack, MapsDirectionsSubway, NavigationChevronRight, EditorMultilineChart, ActionAccountCircle, AvPlayCircleFilled, HardwareGamepad, ActionThumbUp, CommunicationVoicemail, MapsPersonPin, ActionExplore, ImageBlurCircular, ToggleRadioButtonUnchecked, AvWebAsset, NavigationArrowDropRight, CommunicationEmail, CommunicationForum, ImageBurstMode, NavigationRefresh, ActionAssignment, CommunicationNoSim, CommunicationPhone, ActionOpacity, ImageCropLandscape, TableRowColumn, TextField, ActionSettingsApplications, AvAddToQueue, NavigationMoreHoriz, DeviceAccessTime, PopoverAnimationVertical, ContentBlock, ContentClear, DeviceGraphicEq, ActionReportProblem, ContentInbox, ContentReply, ImageBrightness1, ImageBrightness2, ImageBrightness3, ImageBrightness4, ImageBrightness5, ImageBrightness6, ImageBrightness7, ActionLockOpen, ContentReplyAll, AvAlbum, AvGames, ActionSettingsRemote, IconButton, AvMovie, AvPause, AvQueue, AvRadio, AlertAddAlert, DeviceWidgets, MapsLocalShipping, ContentRemoveCircle, NotificationTimeToLeave, ActionExtension, ImageGridOff, AvQueuePlayNext, HardwarePhonelinkOff, EditorFormatAlignJustify, CardActions, ImageRotate90DegreesCcw, ActionCheckCircle, ActionBookmark, HardwareMouse, ImageViewComfy, FloatingActionButton, HardwareWatch, ActionChromeReaderMode, EditorInsertChart, ActionLabelOutline, ActionRestorePage, EditorInsertPhoto, EditorAttachFile, ActionShoppingCart, ImageCrop, ImageEdit, ImageFlip, ImageLens, ImageTune, ImageFilterVintage, ToggleStar, ImageTonality, ActionAllOut, HardwareLaptopChromebook, SocialWhatshot, ContentDeleteSweep, ActionBackup, DeviceBrightnessAuto, DeviceBrightnessHigh, ContentContentCut, ContentRemoveCircleOutline, ActionCached, ActionRemoveShoppingCart, AvReplay10, AvReplay30, NotificationVibration, NotificationAirlineSeatFlat, ImageSwitchCamera, AvFastForward, ActionDelete, CommunicationStayPrimaryLandscape, MapsLocalHospital, ActionDonutLarge, DeviceDevices, ActionDonutSmall, ContentMoveToInbox, EditorFormatItalic, ActionAlarmOn, CommunicationBusiness, AvMicOff, Popover, EditorFormatLineSpacing, ActionTrackChanges, ActionVerifiedUser, ContentFlag, ContentLink, ContentMail, ContentRedo, ContentSave, ContentSend, ContentSort, ContentUndo, LinearProgress, ActionDeleteForever, ActionViewHeadline, PlacesRoomService, ActionTimeline, ActionGetApp, CommunicationCallReceived, ActionAndroid, PlacesBusinessCenter, NotificationEventBusy, NotificationEventNote, EditorDragHandle, DeviceSignalCellular0Bar, DeviceSignalCellular1Bar, DeviceSignalCellular2Bar, DeviceSignalCellular3Bar, DeviceSignalCellular4Bar, DeviceSignalCellularNull, PlacesAcUnit, ImageTagFaces, ActionPanTool, MapsLocalDrink, MapsLocalHotel, DeviceSignalWifi3BarLock, MapsEvStation, ActionDateRange, MapsLocalOffer, ActionPayment, MapsLocalPhone, MapsLocalPizza, AvRepeat, AvReplay, ListItem, MapsLocalAirport, EditorVerticalAlignBottom, AvVideoLibrary, Typography, PlacesCasino, EditorVerticalAlignCenter, ImageFilter9Plus, ImageWbIridescent, AvSnooze, ActionOpenInBrowser, ImageFilterBAndW, ActionLaunch, ImageFilterDrama, HardwareDeviceHub, DatePickerDialog, ImagePhotoAlbum, EditorInsertComment, NotificationAirlineSeatLegroomNormal, NotificationAirlineSeatReclineNormal, MapsLocalPostOffice, MapsTransferWithinAStation, EditorFormatShapes, MapsFlight, ImageColorize, DeviceAirplanemodeInactive, ImageCropPortrait, ImageHdrWeak, ImageFlashAuto, AvForward10, AvForward30, TableFooter, ActionSettingsPhone, ActionSettingsPower, ImageHealing, ActionSettingsVoice, NotificationAirlineSeatReclineExtra, ActionPictureInPicture, ActionPermPhoneMsg, PlacesHotTub, NavigationUnfoldLess, NavigationUnfoldMore, Checkbox, TableHeader, RefreshIndicator, ActionAddShoppingCart, MapsLocalParking, AvVolumeOff, ActionRedeem, CommunicationChatBubbleOutline, NotificationNetworkLocked, DeviceSettingsSystemDaydream, DeviceWifiLock, MapsLocalFlorist, ActionRowing, PlacesBeachAccess, DeviceBattery20, DeviceBattery30, DeviceBattery50, DeviceBattery60, DeviceBattery80, DeviceBattery90, BottomNavigationItem, ActionSearch, HardwareComputer, NotificationSmsFailed, ActionEventSeat, HardwareCast, HardwareDock, HardwarePhoneAndroid, MapsLayers, HardwareToys, NavigationLastPage, AvShuffle, ImageCompare, DeviceAddAlarm, ActionOfflinePin, ActionUpdate, ActionSettingsOverscan, DeviceLocationSearching, ActionLightbulbOutline, CardMedia, PlacesPool, CardTitle, ToggleStarHalf, CircularProgress, MapsNearMe, ActionLanguage, HardwareKeyboardTab, ActionAssignmentReturned, DeviceDataUsage, EditorHighlight, CommunicationPortableWifiOff, ToggleIndeterminateCheckBox, DeviceGpsFixed, ImageExposurePlus1, ImageExposurePlus2, ActionPolymer, ImageStraighten, ActionViewAgenda, HardwareKeyboardBackspace, NotificationDriveEtafs.js:652
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'test/build/material-ui/index.material-ui/styles/colors.kt'
    at Object.fs.openSync (fs.js:652:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at translateToDir (/Users/***/Documents/github/create-react-kotlin-app/node_modules/ts2kt/ts2kt.js:4582:20)
    at main (/Users/***/Documents/github/create-react-kotlin-app/node_modules/ts2kt/ts2kt.js:4764:5)
    at /Users/***/Documents/github/create-react-kotlin-app/node_modules/ts2kt/ts2kt.js:5588:3
    at Object.<anonymous> (/Users/***/Documents/github/create-react-kotlin-app/node_modules/ts2kt/ts2kt.js:5591:2)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
```

**Comment by ScottPierce** [comment]
Seeing this too. It was sporadic at first, but now I can't seem to even get past it.

```
ts2kt version: 0.0.20
Converting globals.d.ts
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'globals.d.ts'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at getScriptSnapshotFromFile (/usr/local/lib/node_modules/ts2kt/ts2kt.js:5180:46)
    at translate (/usr/local/lib/node_modules/ts2kt/ts2kt.js:5388:87)
    at translateToDir (/usr/local/lib/node_modules/ts2kt/ts2kt.js:4969:26)
    at main (/usr/local/lib/node_modules/ts2kt/ts2kt.js:5169:5)
    at /usr/local/lib/node_modules/ts2kt/ts2kt.js:6011:3
    at Object.<anonymous> (/usr/local/lib/node_modules/ts2kt/ts2kt.js:6014:2)
    at Module._compile (module.js:541:32)
```

**Comment by bashor** [comment]
Looks like the original issue is fixed!

@ScottPierce please create separate issue for your case if it's still actual

**Comment by iamBedant** [comment]
@bashor Its not fixed yet. Getting the same issue.

**Comment by bashor** [comment]
@iamBedant which one? Which version of ts2kt fo do you use?

**Comment by iamBedant** [comment]
I am using ts2kt version: 0.1.0

**Comment by bashor** [comment]
@iamBedant could you please provide exact commands to reproduce? 
Is the destination directory exist?
