### ISSUE TITLE
NotImplementedError while converting node mappings

### ISSUE THREAD

**Issue by diklimchuk** [Kotlin/ts2kt#72]
Running `ts2kt DefinitelyTyped/types/node/v8/index.d.ts -d headers` gives me this error:

```
ts2kt version: 0.1.0
Converting DefinitelyTyped/types/node/v8/index.d.ts
ts2kt: "StringLiteral" kind unsupported yet here! (DefinitelyTyped/types/node/v8/index.d.ts:125:27 to 126:10)
ts2kt: "StringLiteral" kind unsupported yet here! (DefinitelyTyped/types/node/v8/index.d.ts:126:53 to 127:12)
ts2kt: "StringLiteral" kind unsupported yet here! (DefinitelyTyped/types/node/v8/index.d.ts:127:55 to 128:12)

/usr/lib/node_modules/ts2kt/ts2kt.js:1698
    throw new NotImplementedError_init();
    ^
NotImplementedError: An operation is not implemented.
    at TsClassToKt.Visitor.visitConstructSignatureDeclaration_cz84f8$ (/usr/lib/node_modules/ts2kt/ts2kt.js:1698:11)
    at visitNode (/usr/lib/node_modules/ts2kt/ts2kt.js:2272:15)
    at /usr/lib/node_modules/ts2kt/ts2kt.js:2233:7
    at visitNodes (/usr/lib/node_modules/ts2kt/node_modules/typescript/lib/typescript.js:12699:30)
    at forEachChild (/usr/lib/node_modules/ts2kt/node_modules/typescript/lib/typescript.js:12792:24)
    at forEachChild_0 (/usr/lib/node_modules/ts2kt/ts2kt.js:2238:5)
    at TypeScriptToKotlin.tryTranslateTypeLiteralAsObject_0 (/usr/lib/node_modules/ts2kt/ts2kt.js:3154:5)
    at TypeScriptToKotlin.visitVariableStatement_x0poxd$ (/usr/lib/node_modules/ts2kt/ts2kt.js:3141:29)
    at visitNode (/usr/lib/node_modules/ts2kt/ts2kt.js:2251:15)
    at /usr/lib/node_modules/ts2kt/ts2kt.js:2233:7
```
The last version it doesn't crash is 0.0.18

**Comment by bashor** [comment]
Fixed in 0.1.1
